Make dummy URL even more visible

diff --git a/.github/workflows/third_party.yml b/.github/workflows/third_party.yml
--- a/.github/workflows/third_party.yml
+++ b/.github/workflows/third_party.yml
@@ -30,7 +30,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Print URL
-        run: echo '::error::Run URL ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+        run: |
+          echo '::error::Run URL ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+          exit 1
   pydantic:
     name: pydantic tests
     if: >-
